linters-settings:
  dupl:
    threshold: 150
  funlen:
    lines: 150
    statements: 80
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
      - sloppyReassign
      - unnecessaryBlock
      - paramTypeCombine
  gocyclo:
    min-complexity: 25
  goimports:
    local-prefixes: github.com/Over-knight/Lujay-assesment
  govet:
    disable:
      - shadow
  lll:
    line-length: 200
  misspell:
    locale: US
    ignore-words:
      - cancelled

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
